class DataFields:
    screen_x = 'Screen X'
    screen_y = 'Screen Y'
    root_virtual_x = 'Root Virtual X'
    root_virtual_y = 'Root Virtual Y'
    iterations = 'Iterations'
    converged = 'Converged'
    label = 'Label'
    color_r = 'Color Red'
    color_g = 'Color Green'
    color_b = 'Color Blue'
    color_a = 'Color Alpha'
